#!/bin/sh
set -eu
app_dir=$(dirname "$(readlink -f "$0")")
export PYTHONPATH="$app_dir/lib:$app_dir"
export PYTHONNOUSERSITE=1
export PYTHONDONTWRITEBYTECODE=1
exec /usr/bin/python3 -m nightread "$@"
